name: Unit Tests
on: [push, pull_request]

jobs:
  Run_UT:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: git ls-tree
        run: |
          python -m unittest discover -p "*_test.py" src

